### PR TITLE
Feature/cards

### PR DESCRIPTION
**Pull request by isaif**
- Improve styling of card component
- Add z-index to navbar to put it on top of all elements
- Add grid layout to "SpeakersSection" component
- Duplicated index page to speakers page for testing the changes

### CODE REVIEW

**Comment by isaif** [comment]
Top alignment in cards looks better

## Top alignment
image

## Centre alignment

image

**Comment by isaif** [comment]
Preview link https://deploy-preview-73--keen-otter-8dfbae.netlify.app/speakers

**Comment by eruizc-dev** [comment]
Looks amazing! Needs some tweaks for mobile (360px) and we merge it

image

**Review by eruizc-dev — CHANGES_REQUESTED** [review]
Looks amazing! Needs some tweaks for mobile (360px) and we merge it

image

**Comment by isaif** [comment]
> Looks amazing! Needs some tweaks for mobile (360px) and we merge it
> 
> image

What changes do you suggest?

**Comment by eruizc-dev** [comment]
Shrinking it so it doesn't overflow would be fine I guess

**Comment by isaif** [comment]
@eruizc-dev check if it is good now 

image

**Review by eruizc-dev — APPROVED** [review]
Merge it & Ship it

**Pull request merged**
